env: local
debug: true
secret-key: secret
database:
  host: localhost
  port: 5656
  username: alfar
  password: 'testabcde'
  dbname: alfarpos
  dbname-test: alfarpos_test
shop-profile:
  name: 'TOKO ALFAR'
  description: 'TOKO SERBA ADA'
  address: 'KETAON RT 7 RW 1, BANYUDONO, BOYOLALI 57373'
  phone: '(0276) 3283720'
  npwp: '192810982901809'
  thankyou_message: 'TERIMA KASIH ATAS KUNJUNGAN ANDA'
  foot_note: 'BARANG YANG SUDAH DIBELI TIDAK DAPAT DIKEMBALIKAN'
log:
  path_info: '/var/log/alfarpos/info.log'
  path_debug: '/var/log/alfarpos/debug.log'
