env: production
debug: true
secret-key: secret
database:
  host: localhost
  port: 5432
  username: almanalfaruq
  password: ''
  dbname: alfarpos
  dbname-test: alfarpos_test
shop-profile:
  name: 'Toko Alfar'
  description: 'Toko Serba Ada'
  address: 'Ketaon RT 7 RW 1, Banyudono, Boyolali 57373'
  phone: '(0276) 3283720'
  npwp: '192810982901809'
  thankyou_message: 'Terima kasih atas kunjungan anda'
  foot_note: 'Barang yang sudah dibeli tidak dapat dikembalikan'
log:
  path_info: '/var/log/alfarpos/info.log'
  path_debug: '/var/log/alfarpos/debug.log'
