version: '3.8'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: alfarpos      # Name of the default database to create
      POSTGRES_USER: alfar        # Username for the PostgreSQL user
      POSTGRES_PASSWORD: testabcde # Password for the PostgreSQL user
    ports:
      - "5656:5432"                 # Map the container port to the host
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage for data
  memcached:
    image: memcached:1.6.14-alpine
    ports:
      - "11211:11211"

volumes:
  postgres_data: